### ISSUE TITLE
Theo doesn't parse hex values for color

### ISSUE THREAD

**Issue by MindSculpt** [salesforce-ux/gulp-theo#3]
Unless I'm missing something, if I have the following in my `aliases.yml`:

```
---
aliases:
  # colors
  white: #fff
  black: #000
```

The output doesn't read hex values and I get:

```
$white: rgb(0, 0, 0);
$black rgb(0, 0, 0);

```

...for all colors. Related or not, I'm also noticing the ability to just pass through token values that don't necessarily map to one of your existing formats. Might be worth allowing a general `type/category` for this.

Also since this technically generates a variables file, would it make sense to add in hardcoded `!default` flags for all outputted sass vars?

**Comment by MindSculpt** [comment]
Nevermind—the hex issue was totally my fault. This works fine.

I would still like your thoughts on those last two items though.

**Comment by julzmon** [comment]
@MindSculpt could you please tell me how you solved the issue? I'm trying to figure this out.

**Comment by MindSculpt** [comment]
@julzmon I wound up adding colors to my `_aliases.yml` file like this:

```
aliases:
  #colors
  white: '#fff'
  black: '#000'
```

Then I created a `_color.yml` file where I have the following:

```
imports:
 - _aliases.yml

props: 
  white: "{!white}"
    type: color
    category: text-color
    comment: ""

  black: "{!black}"
    type: color
    category: text-color
    comment: ""
```
Then obviously import `_color.yml` into your main `app.yml` file. This seems to get around not having categories that map since I'm just using this to generate the tokens, not the styles doc.
